version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  db_server:
    build: .
    entrypoint: gunicorn -b :8080 example.dbapp:init_app()
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - 8081:8080
    depends_on:
      - postgres
  redis:
    image: redis
    ports:
      - 6379:6379
  redis_worker:
    build: .
    entrypoint: rq worker -u redis://redis:6379
    depends_on:
      - redis
  ml_server:
    build: .
    environment:
      - DATABASE_URI=http://db_server:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 8080:8080
    depends_on:
      - redis_worker
      - db_server